### ISSUE TITLE
Make the repository public

### ISSUE THREAD

**Issue by lucaslanek** [gsp-eeg/pygsp2#12]
In GitLab by @aweinstein on May 29, 2024, 05:42

We need to make the PyGSP repo public before PyDay Valpo (2024-06-14). I suggest naming the repo PyGSP2 and adding a note to the README stating that this is a friendly fork of the original repo.

Making the repo public includes:

- Making the repo available at PyPI.
- Making the documentation public in readthedocs.

**Comment by cjotade** [comment]
* Repo already in Pypi https://pypi.org/project/pygsp2/.
* Readthedocs is not working since it takes the documentation from the master branch, we have to update the master branch before fix the documentation, see issue #25 to check updates
