### ISSUE TITLE
Fix link of read-the-docs

### ISSUE THREAD

**Issue by aweinstein** [gsp-eeg/pygsp2#30]
The Read the Docs is linked to branch `22-change-basename-folder-to-pygsp2`. It should point to the branch master.

Note that the link we have is https://pygsp2.readthedocs.io/en/22-change-basename-folder-to-pygsp2/index.html#

It should be:

https://pygsp2.readthedocs.io/en/stable/#

**Comment by lcortesg** [comment]
Doc is linked to `22-change-basename-folder-to-pygsp2` branch until the pending merge to the master branch is approved, until that, the Read the Docs build for the master branch will keep failing, hence the broken link for the latest release [https://pygsp2.readthedocs.io/en/latest/](https://pygsp2.readthedocs.io/en/latest/)

**Comment by cjotade** [comment]
Other option is to create a "stable" branch that has the same information in 22-change-basename-folder-to-pygsp2

**Comment by aweinstein** [comment]
I did a review on #22. As soon as @lcortesg and @cjotade address my comments, we can do the merge and fix this issue.
