### ISSUE TITLE
Add the project to conda-forge

### ISSUE THREAD

**Issue by aweinstein** [gsp-eeg/pygsp2#31]
Add the project to [conda-forge](https://conda-forge.org/) to make it possible to install PyGSP2 with

```
$ conda install -c conda-forge pygsp2
```

**Comment by lcortesg** [comment]
Package submitted to Conda-Forge, revision pending

**Comment by lcortesg** [comment]
> Package submitted to Conda-Forge, revision pending

Conda-forge revision passed
