### ISSUE TITLE
Define the current version 

### ISSUE THREAD

**Issue by aweinstein** [gsp-eeg/PyGSP2#36]
Somewhere, we push the version from 0.5 to 2.0. I think this change is too large. At most, we should be at 1.0. Or perhaps just 0.6. Also, the version change should be reflected in the `__init__.py` file and the changelog.

We need to have a meeting to discuss these details.

**Comment by aweinstein** [comment]
I think we should agree to use [semantic versioning](https://semver.org/) (it's what most packages use).

Under this definition, I think we should release PyGSP2 with version 0.6.0.

Opinions @cjotade, @lcortesg, @Jrodino ?

**Comment by lcortesg** [comment]
Given that PyPi will not allow a name/version re-use, i think we should stick to the current version name for the sake of simplicity.

Another option would be to completely delete the PyPi PyGSP2 project, but there is no certainty that this way we'll be clear of the name re-use restriction.

**Comment by aweinstein** [comment]
OK.
